name: Publish

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed

jobs:
  build-n-publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install setuptools wheel
      - name: Build a binary wheel and a source tarball
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish distribution 📦 to PyPI
        # https://github.community/t/workflow-run-doent-preserve-github-ref/155148/4
        if: startsWith(github.event.workflow_run.head_branch, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
